// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	accounts "github.com/leonardosaid/stc/accounts/pkg/stc-sdk/session/accounts"

	mock "github.com/stretchr/testify/mock"
)

// ServiceClients is an autogenerated mock type for the ServiceClients type
type ServiceClients struct {
	mock.Mock
}

// GetAccountServiceClient provides a mock function with given fields:
func (_m *ServiceClients) GetAccountServiceClient() accounts.Client {
	ret := _m.Called()

	var r0 accounts.Client
	if rf, ok := ret.Get(0).(func() accounts.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(accounts.Client)
		}
	}

	return r0
}

type mockConstructorTestingTNewServiceClients interface {
	mock.TestingT
	Cleanup(func())
}

// NewServiceClients creates a new instance of ServiceClients. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServiceClients(t mockConstructorTestingTNewServiceClients) *ServiceClients {
	mock := &ServiceClients{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
