// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	jwt "github.com/golang-jwt/jwt"
	domain "github.com/leonardosaid/stc/accounts/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// TransferUseCase is an autogenerated mock type for the TransferUseCase type
type TransferUseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1, _a2
func (_m *TransferUseCase) Create(_a0 context.Context, _a1 *domain.Transfer, _a2 *jwt.Token) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Transfer, *jwt.Token) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListByAccountID provides a mock function with given fields: _a0, _a1
func (_m *TransferUseCase) ListByAccountID(_a0 context.Context, _a1 *jwt.Token) ([]domain.Transfer, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []domain.Transfer
	if rf, ok := ret.Get(0).(func(context.Context, *jwt.Token) []domain.Transfer); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transfer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *jwt.Token) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTransferUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransferUseCase creates a new instance of TransferUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransferUseCase(t mockConstructorTestingTNewTransferUseCase) *TransferUseCase {
	mock := &TransferUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
